# Generated by Django 3.0.3 on 2020-02-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.PositiveIntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2, verbose_name='性别')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='国家')),
                ('bron_date', models.DateField(blank=True, verbose_name='出生日期')),
                ('dead_date', models.DateField(blank=True, verbose_name='逝世日期')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='头衔')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '作者',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别')),
                ('is_nav', models.BooleanField(default=True, verbose_name='是否展示')),
                ('sequence', models.PositiveIntegerField(default='255', verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '类别',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('translator', models.CharField(blank=True, max_length=50, verbose_name='译者')),
                ('publisher', models.CharField(max_length=50, verbose_name='出版社')),
                ('published_date', models.DateTimeField(verbose_name='出版时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pic', models.ImageField(blank=True, upload_to='img', verbose_name='图片')),
                ('interduction', models.TextField(max_length='512', verbose_name='简介')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '书籍',
            },
        ),
    ]
