# Generated by Django 3.0.3 on 2020-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200228_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bron_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='author',
            name='dead_date',
            field=models.DateField(blank=True, null=True, verbose_name='逝世日期'),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='头衔'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='books',
            name='translator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='译者'),
        ),
    ]
